- [2048_fibonacci](https://github.com/perguto/2048_fibonacci): 2048, but with Fibonacci numbers
- [Ace Attorney Trilogy SiIvagunner Mod](https://github.com/perguto/Ace-Attorney-Trilogy-SiIvagunner-Mod): Please read the updated autopsy report.
- [Ace Attorney Trilogy SiIvagunner Mod 3DS](https://github.com/perguto/Ace-Attorney-Trilogy-SiIvagunner-Mod-3DS): Please read the updated autopsy report.
- [AHK Docs_DE](https://github.com/perguto/AHK-Docs_DE): Deutsche Dokumentation für AutoHotkey 
- [AHK Docs_EN](https://github.com/perguto/AHK-Docs_EN): Documentation for AutoHotkey
- [AHK Docs_ES](https://github.com/perguto/AHK-Docs_ES): Spanish translation of AutoHotkey's documentation 
- [AHK Docs_FR](https://github.com/perguto/AHK-Docs_FR): French translation of AutoHotkey's documentation
- [AHK Docs_KO](https://github.com/perguto/AHK-Docs_KO): Korean translation of AutoHotkey's documentation
- [AHK Docs_PT](https://github.com/perguto/AHK-Docs_PT): Brazilian Portuguese translation of AutoHotkey's documentation
- [AHK Docs_ZH](https://github.com/perguto/AHK-Docs_ZH): 个人主页, Autohotkey  中文帮助, 自用脚本介绍
- [AHK Scripts](https://github.com/perguto/AHK-Scripts): own_ahk_scripts
- [AM2R SiIvagunner Mod](https://github.com/perguto/AM2R-SiIvagunner-Mod): So far only alternate music for hydro station
- [Brawl SiIvagunner Mod](https://github.com/perguto/Brawl-SiIvagunner-Mod): The highest quality rips for Super Smash Bros. Brawl!
- [Country Flag Emojis for Windows](https://github.com/perguto/Country-Flag-Emojis-for-Windows): Get all country flag emojis to display properly on Windows, as well as generally better Google Emojis!
- [Craiyon Download Button](https://github.com/perguto/Craiyon-Download-Button): Download all generated images on craiyon.com in original quality with one click!
- [Deltarune SiIvagunner Mod](https://github.com/perguto/Deltarune-SiIvagunner-Mod): Enjoy Deltarunne with the highest quality music!
- [funny_gam](https://github.com/perguto/funny_gam): funny gam
- [goggle](https://github.com/perguto/goggle): goggle
- [Grand Story for 3DS](https://github.com/perguto/Grand-Story-for-3DS): null
- [Hanzi Readings Comparison](https://github.com/perguto/Hanzi-Readings-Comparison): Table of Chinese characters with their Middle Chinese, reconstructed Old Chinese and Sino-Xenic readings
- [Hotline Miami 2 SiIvagunner Mod](https://github.com/perguto/Hotline-Miami-2-SiIvagunner-Mod): You really enjoy listening to high-quality rips, don't you?
- [Hotline Miami SiIvagunner Mod](https://github.com/perguto/Hotline-Miami-SiIvagunner-Mod): Gotta get a high quality rip!
- [math_game](https://github.com/perguto/math_game): null
- [Meme It](https://github.com/perguto/Meme-It): Meme-it is a simple meme generator built using Javascript library Fabric.Js, and it allows you to manipulate text or images on a chosen meme template.
- [Old Hangul Input Method](https://github.com/perguto/Old-Hangul-Input-Method): Javascript-based IME for typing archaic Korean Hangul letters (e.g. ㅸ, ㅿ, ㅵ) easily
- [pandoc unicode math](https://github.com/perguto/pandoc-unicode-math): Replace Unicode symbols by equivalent Latex commands
- [pandoc_manual](https://github.com/perguto/pandoc_manual): pandoc_manual
- [pandoc_test](https://github.com/perguto/pandoc_test): pandoc_test
- [Papers Please Borat Mod](https://github.com/perguto/Papers-Please-Borat-Mod): Telegame for Instruction Apprenticeship of Border Supervisor of Glorious Nation of Kazakhstan Protecting Country from Uzbekistan Infiltration
- [pdf.js](https://github.com/perguto/pdf.js): PDF Reader in JavaScript
- [pdfjs](https://github.com/perguto/pdfjs): null
- [perguto.github.io](https://github.com/perguto/perguto.github.io): My site
- [PhoenixWrightTrilogyTools](https://github.com/perguto/PhoenixWrightTrilogyTools): Tools for Phoenix Wright: Ace Attorney Trilogy (Steam version)
- [Shantae and the Seven Sirens Siivagunner Mod](https://github.com/perguto/Shantae-and-the-Seven-Sirens-Siivagunner-Mod): This little mod replaces some songs in "Shantae and the Seven Sirens" with their respective Siivagunner rips. Enjoy!
- [SiIvagunner all rips playlist](https://github.com/perguto/SiIvagunner-all-rips-playlist): This is a playlist of all SiIvagunner rips from newest to oldest
- [Sonic Robo Blast 2 Siivagunner Mod](https://github.com/perguto/Sonic-Robo-Blast-2-Siivagunner-Mod): null
- [STk](https://github.com/perguto/STk): STk is the ancestor of STklos (https://stklos.net)  This repository contains fixes to allow the compilation of 4.0.1 on modern versions of GCC
- [sus chess](https://github.com/perguto/sus-chess): A very sussy mod for "5D Chess With Multiverse Time Travel"
- [Syobon Action Siivagunner Mod](https://github.com/perguto/Syobon-Action-Siivagunner-Mod): Only the highest quality rips for this high quality jump'n'run!
- [Undertale Siivagunner Mod](https://github.com/perguto/Undertale-Siivagunner-Mod): Enjoy Undertale with the highest quality rips!
- [Video Screenshot Extension](https://github.com/perguto/Video-Screenshot-Extension): Take a screenshot of any video on any website, in the best quality and without unwanted UI elements!
- [vimium c](https://github.com/perguto/vimium-c): A keyboard shortcut browser extension for keyboard-based navigation and tab operations with an advanced omnibar
- [VVVVVV SiIvagunner Mod](https://github.com/perguto/VVVVVV-SiIvagunner-Mod): Adds all the SiIvagunner and Timmy Turner's Grand Dad Song Parodies to VVVVVV
- [Wiktionary Lookup](https://github.com/perguto/Wiktionary-Lookup): null
- [XTranslate without malware](https://github.com/perguto/XTranslate-without-malware): Easy translate text on web pages (chrome extension)
